version: '3'

services:
  frontend: 
    image: andrewriabets/time-app-frontend-dev
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
  api:
    image: andrewriabets/time-app-api-dev
    restart: always
    ports:
      - '5555:5000'
    depends_on:
      - mysql
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - MySQL_HOST=mysql
      - MySQL_USER=root
      - MySQL_PORT=3306 
      - MySQL_PASSWORD=password
      - MySQL_DB=time_db
  mysql: 
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=time_db
    volumes:
      - mysql_data_pub:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
volumes:
  mysql_data_pub: